import { randomBytes } from "node:crypto";import { db,query } from "../db.js";
export type SubscriptionStatus="APPROVAL_PENDING"|"APPROVED"|"ACTIVE"|"SUSPENDED"|"CANCELLED"|"EXPIRED"|"INACTIVE";export type SubscriptionRecord={userId:string;paypalSubscriptionId:string;paypalPlanId:string;status:SubscriptionStatus;startTime?:string;nextBillingTime?:string;statusUpdateTime?:string;subscriberEmail?:string;createdAt:string;updatedAt:string};
const subscriptions=new Map<string,SubscriptionRecord>(),checkouts=new Map<string,{token:string;userId:string;createdAt:string;expiresAt:string;consumedAt?:string}>(),webhookEvents=new Set<string>();
const selectSub='SELECT user_id AS "userId",paypal_subscription_id AS "paypalSubscriptionId",paypal_plan_id AS "paypalPlanId",status,start_time AS "startTime",next_billing_time AS "nextBillingTime",status_update_time AS "statusUpdateTime",subscriber_email AS "subscriberEmail",created_at AS "createdAt",updated_at AS "updatedAt" FROM subscriptions';
export async function createCheckoutToken(userId:string){const now=new Date(),item={token:randomBytes(24).toString("base64url"),userId,createdAt:now.toISOString(),expiresAt:new Date(now.getTime()+900000).toISOString()};if(db){await query('INSERT INTO checkout_tokens (token,user_id,created_at,expires_at) VALUES ($1,$2,$3,$4)',[item.token,userId,item.createdAt,item.expiresAt]);return item}checkouts.set(item.token,item);return item}
export async function consumeCheckoutToken(token:string,userId:string){if(db){const r=await query('UPDATE checkout_tokens SET consumed_at=NOW() WHERE token=$1 AND user_id=$2 AND consumed_at IS NULL AND expires_at>NOW() RETURNING token',[token,userId]);return Boolean(r[0])}const e=checkouts.get(token);if(!e||e.userId!==userId||e.consumedAt||Date.parse(e.expiresAt)<=Date.now())return false;e.consumedAt=new Date().toISOString();return true}
export async function getSubscriptionForUser(userId:string){if(db){const r=await query<SubscriptionRecord>(selectSub+' WHERE user_id=$1 ORDER BY updated_at DESC LIMIT 1',[userId]);return r[0]}return[...subscriptions.values()].filter(x=>x.userId===userId).sort((a,b)=>Date.parse(b.updatedAt)-Date.parse(a.updatedAt))[0]}
export async function getSubscriptionByPayPalId(id:string){if(db){const r=await query<SubscriptionRecord>(selectSub+' WHERE paypal_subscription_id=$1 LIMIT 1',[id]);return r[0]}return subscriptions.get(id)}
export async function upsertSubscription(input:Omit<SubscriptionRecord,"createdAt"|"updatedAt">){const now=new Date().toISOString();if(db){const old=await query<{createdAt:string}>('SELECT created_at AS "createdAt" FROM subscriptions WHERE paypal_subscription_id=$1',[input.paypalSubscriptionId]);await query('INSERT INTO subscriptions (user_id,paypal_subscription_id,paypal_plan_id,status,start_time,next_billing_time,status_update_time,subscriber_email,created_at,updated_at) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$10) ON CONFLICT (paypal_subscription_id) DO UPDATE SET status=EXCLUDED.status,start_time=EXCLUDED.start_time,next_billing_time=EXCLUDED.next_billing_time,status_update_time=EXCLUDED.status_update_time,subscriber_email=EXCLUDED.subscriber_email,updated_at=EXCLUDED.updated_at',[input.userId,input.paypalSubscriptionId,input.paypalPlanId,input.status,input.startTime??null,input.nextBillingTime??null,input.statusUpdateTime??null,input.subscriberEmail??null,old[0]?.createdAt??now]);return{...input,createdAt:old[0]?.createdAt??now,updatedAt:now}}const old=subscriptions.get(input.paypalSubscriptionId),item={...input,createdAt:old?.createdAt??now,updatedAt:now};subscriptions.set(item.paypalSubscriptionId,item);return item}
export async function hasActiveSubscription(userId:string){return(await getSubscriptionForUser(userId))?.status==="ACTIVE"}
export async function recordWebhookEvent(id:string){if(db){const r=await query('INSERT INTO paypal_webhook_events (event_id,received_at) VALUES ($1,NOW()) ON CONFLICT (event_id) DO NOTHING RETURNING event_id',[id]);return Boolean(r[0])}if(webhookEvents.has(id))return false;webhookEvents.add(id);return true}
export async function hasWebhookEvent(id:string){if(db){const r=await query('SELECT event_id FROM paypal_webhook_events WHERE event_id=$1',[id]);return Boolean(r[0])}return webhookEvents.has(id)}
